---

window:
    # As the resolution of an Apple II is 280x192px,
    # the native presentation mode may be too small.
    zoom: 3

cpu:
    # Usual clock settings are 0.98 and 3.58 (aka 1MHz and 4MHz).
    mhz: 0.98

disk:
    # File paths of "inserted" Disk 1 and Disk 2 images.
    # Paths can be HTTP URLs. Fetched images are not saved.
    # Using the -1 and -2 options overrides this setting.
    drive-1: ""
    drive-2: ""

render:
    mono:
        color: 0x00B500FF

    lores:
        colors: [
            0x000000FF, # 0 Black
            0x9A2110FF, # 1 Magenta
            0x3C22A5FF, # 2 Dark Blue
            0xA13FB7FF, # 3 Purple
            0x07653EFF, # 4 Dark Green
            0x7B7E80FF, # 5 Dark Gray
            0x308FE3FF, # 6 Medium Blue
            0xADD8E6FF, # 7 Light Blue
            0x8B4513FF, # 8 Brown
            0xC77028FF, # 9 Orange
            0x7B7E80FF, # A Gray
            0xF39AC2FF, # B Pink
            0x2FB81FFF, # C Green
            0xFFFF80FF, # D Yellow
            0x6EE1C0FF, # E Aqua
            0xFFFFFFFF, # F White
        ]
    hires:
        colors: [
            0x000000FF, # 0 Black
            0xA13FB7FF, # 2 Purple
            0x2FB81FFF, # 1 Green
            0xFFFFFFFF, # 3 White
            0x000000FF, # 4 Black
            0x308FE3FF, # 6 Med Blue
            0xC77028FF, # 5 Orange
            0xFFFFFFFF, # 7 White
        ]
